
module "tfpData" {
  export default ()  {        
    productTypes = {
      1: { id: 1, name: 'pens', desc: 'Pen', img: 'pen.png'},
      2: { id: 2, name: 'peppermills', desc: 'Peppermill', img: 'peppermill.png'},
      3: { id: 3, name: 'pizzacutters', desc: 'Pizza Cutter', img: 'pizzacutter.png'},
      4: { id: 4, name: 'icecreamscoops', desc: 'Ice Cream Scoop', img: 'icecreamscoop.png'},
      5: { id: 5, name: 'seamrippers', desc: 'Seam Ripper', img: 'seamripper.png'},
      6: { id: 6, name: 'corkscrews', desc: 'Corkscrew', img: 'corkscrew.png'},
      7: { id: 7, name: 'shavingkits', desc: 'Shavingkit', img: 'shavingkit.jpg'},
      8: { id: 8, name: 'lamps', desc: 'Lamp', img: 'steampunklamp.jpg'},
      9: { id: 9, name: 'clocks', desc: 'Clock', img: 'clocks.jpg'},
      10: { id: 10, name: 'maps', desc: 'Map', img: 'maps.jpg'}
    },
    productItems = {
      1: { id: 1, productTypeId: 1, name: '30/30 lever', desc: '30/30 lever', img: 'pens/lever.jpg', price: '75'  },
      2: { id: 2, productTypeId: 1, name: '30 cal', desc: '30 cal', img: 'pens/30cal.png', price: '75'  },
      3: { id: 3, productTypeId: 1, name: '50 cal', desc: '50 cal', img: 'pens/peppermill.png', price: '55'  },
      4: { id: 4, productTypeId: 1, name: 'celtic', desc: 'celtic', img: 'pens/celtic.jpg', price: '95'  },
      5: { id: 5, productTypeId: 1, name: 'cowboy', desc: 'cowboy', img: 'pens/cowboy.jpg', price: '85'  },
      6: { id: 6, productTypeId: 1, name: 'crystal', desc: 'crystal', img: 'pens/princess.jpg', price: '45'  },
      7: { id: 7, productTypeId: 1, name: 'dragon', desc: 'dragon', img: 'pens/dragon.jpg', price: '95'  },
      8: { id: 8, productTypeId: 1, name: 'firefighter', desc: 'firefighter', img: 'pens/firefighter.jpg', price: '120'  },
      9: { id: 9, productTypeId: 1, name: 'flyfish', desc: 'flyfish', img: 'pens/flyfish.jpg', price: '75'  },
      10: { id: 10, productTypeId: 1, name: 'harley', desc: 'harley', img: 'pens/harley.jpg', price: '95'  },
      11: { id: 11, productTypeId: 1, name: 'revolver', desc: 'revolver', img: 'pens/revolver.jpg', price: '95'  },
      12: { id: 12, productTypeId: 1, name: 'shotgun', desc: 'shotgun', img: 'pens/shotgun.jpg', price: '95'  },
      13: { id: 13, productTypeId: 1, name: 'skeletonkey', desc: 'skeletonkey', img: 'pens/peppermill.jpg', price: '85'  },
      14: { id: 14, productTypeId: 1, name: 'skull', desc: 'skull', img: 'pens/skull.jpg', price: '85'  },
      15: { id: 15, productTypeId: 1, name: 'steampunk', desc: 'steampunk', img: 'pens/steampunk.jpg', price: '95'  },
      16: { id: 16, productTypeId: 1, name: 'stylus', desc: 'stylus', img: 'pens/stylus.jpg', price: '55'  },
      17: { id: 17, productTypeId: 1, name: 'tech', desc: 'tech', img: 'pens/tech.jpg', price: '55'  },
      18: { id: 18, productTypeId: 1, name: 'victoriacross', desc: 'victoriacross', img: 'pens/victoriacross.jpg', price: '55'  },
      19: { id: 19, productTypeId: 2, name: 'b_w_ebony', desc: 'b_w_ebony', img: 'peppermills/peppermill.png', price: '150'  },
      20: { id: 20, productTypeId: 2, name: 'bubinga', desc: 'bubinga', img: 'peppermills/peppermill.png', price: '85'  },
      21: { id: 21, productTypeId: 2, name: 'burnt cedar', desc: 'burnt cedar', img: 'peppermills/peppermill.png', price: '75'  },
      22: { id: 22, productTypeId: 2, name: 'burmese redwodd', desc: 'burmese redwodd', img: 'peppermills/peppermill.png', price: '85'  },
      23: { id: 23, productTypeId: 2, name: 'burnt catalpa', desc: 'burnt catalpa', img: 'peppermills/peppermill.png', price: '75'  },
      24: { id: 24, productTypeId: 2, name: 'burnt elm', desc: 'burnt elm', img: 'peppermills/dragon.png', price: '75'  },
      25: { id: 25, productTypeId: 2, name: 'catalpa', desc: 'catalpa', img: 'peppermills/peppermill.png', price: '75'  },
      26: { id: 26, productTypeId: 2, name: 'cedar', desc: 'cedar', img: 'peppermills/peppermill.png', price: '75'  },
      27: { id: 27, productTypeId: 2, name: 'cherry', desc: 'cherry', img: 'peppermills/peppermill.png', price: '85'  },
      28: { id: 28, productTypeId: 2, name: 'elm', desc: 'elm', img: 'peppermills/peppermill.png', price: '75'  },
      29: { id: 29, productTypeId: 2, name: 'indian redwood', desc: 'indian redwood', img: 'peppermills/peppermill.png', price: '85'  },
      30: { id: 30, productTypeId: 2, name: 'laminatedblue', desc: 'laminatedblue', img: 'peppermills/peppermill.png', price: '85'  },
      31: { id: 31, productTypeId: 2, name: 'laminatedgreen', desc: 'laminatedgreen', img: 'peppermills/peppermill.png', price: '85'  },
      32: { id: 32, productTypeId: 2, name: 'laminatedred', desc: 'laminatedred', img: 'peppermills/peppermill.png', price: '85'  },
      33: { id: 33, productTypeId: 2, name: 'laminatedsilverblue', desc: 'laminatedsilverblue', img: 'peppermills/peppermill.png', price: '85'  },
      34: { id: 34, productTypeId: 2, name: 'laminatedsilvergreen', desc: 'laminatedsilvergreen', img: 'peppermills/peppermill.png', price: '85'  },
      35: { id: 35, productTypeId: 2, name: 'laminatedsilverred', desc: 'laminatedsilverred', img: 'peppermills/peppermill.png', price: '85'  },
      36: { id: 36, productTypeId: 2, name: 'mahogany', desc: 'mahogany', img: 'peppermills/peppermill.png', price: '85'  },
      37: { id: 37, productTypeId: 2, name: 'oak', desc: 'oak', img: 'peppermills/shotgun.png', price: '85'  },
      38: { id: 38, productTypeId: 2, name: 'padauk', desc: 'padauk', img: 'peppermills/peppermill.png', price: '85'  },
      39: { id: 39, productTypeId: 2, name: 'spalted maple', desc: 'spalted maple', img: 'peppermills/peppermill.png', price: '85'  },
      40: { id: 40, productTypeId: 2, name: 'spalted elm', desc: 'spalted elm', img: 'peppermills/peppermill.png', price: '85'  },
      41: { id: 41, productTypeId: 2, name: 'walnut', desc: 'walnut', img: 'peppermills/peppermill.png', price: '85'  },
      42: { id: 42, productTypeId: 3, name: 'burmese redwodd', desc: 'burmese redwodd', img: 'pizzacutters/peppermill.png', price: '60'  },
      43: { id: 43, productTypeId: 3, name: 'catalpa', desc: 'catalpa', img: 'pizzacutters/peppermill.png', price: '60'  },
      44: { id: 44, productTypeId: 3, name: 'cedar', desc: 'cedar', img: 'pizzacutters/peppermill.png', price: '60'  },
      45: { id: 45, productTypeId: 3, name: 'cherry', desc: 'cherry', img: 'pizzacutters/peppermill.png', price: '60'  },
      46: { id: 46, productTypeId: 3, name: 'elm', desc: 'elm', img: 'pizzacutters/peppermill.png', price: '60'  },
      47: { id: 47, productTypeId: 3, name: 'indian redwood', desc: 'indian redwood', img: 'pizzacutters/peppermill.png', price: '60'  },
      48: { id: 48, productTypeId: 3, name: 'laminatedblue', desc: 'laminatedblue', img: 'pizzacutters/peppermill.png', price: '60'  },
      49: { id: 49, productTypeId: 3, name: 'laminatedgreen', desc: 'laminatedgreen', img: 'pizzacutters/peppermill.png', price: '60'  },
      50: { id: 50, productTypeId: 3, name: 'laminatedred', desc: 'laminatedred', img: 'pizzacutters/peppermill.png', price: '60'  },
      51: { id: 51, productTypeId: 3, name: 'laminatedsilverblue', desc: 'laminatedsilverblue', img: 'pizzacutters/peppermill.png', price: '60'  },
      52: { id: 52, productTypeId: 3, name: 'laminatedsilvergreen', desc: 'laminatedsilvergreen', img: 'pizzacutters/peppermill.png', price: '60'  },
      53: { id: 53, productTypeId: 3, name: 'laminatedsilverred', desc: 'laminatedsilverred', img: 'pizzacutters/peppermill.png', price: '60'  },
      54: { id: 54, productTypeId: 3, name: 'mahogany', desc: 'mahogany', img: 'pizzacutters/peppermill.png', price: '60'  },
      55: { id: 55, productTypeId: 3, name: 'oak', desc: 'oak', img: 'pizzacutters/shotgun.png', price: '60'  },
      56: { id: 56, productTypeId: 3, name: 'padauk', desc: 'padauk', img: 'pizzacutters/peppermill.png', price: '60'  },
      57: { id: 57, productTypeId: 3, name: 'spalted maple', desc: 'spalted maple', img: 'pizzacutters/peppermill.png', price: '60'  },
      58: { id: 58, productTypeId: 3, name: 'spalted elm', desc: 'spalted elm', img: 'pizzacutters/peppermill.png', price: '60'  },
      59: { id: 59, productTypeId: 3, name: 'walnut', desc: 'walnut', img: 'pizzacutters/peppermill.png', price: '60'  },
      60: { id: 60, productTypeId: 4, name: 'burmese redwodd', desc: 'burmese redwodd', img: 'peppermills/peppermill.png', price: '60'  },
      61: { id: 61, productTypeId: 4, name: 'catalpa', desc: 'catalpa', img: 'peppermills/peppermill.png', price: '60'  },
      62: { id: 62, productTypeId: 4, name: 'cedar', desc: 'cedar', img: 'peppermills/peppermill.png', price: '60'  },
      63: { id: 63, productTypeId: 4, name: 'cherry', desc: 'cherry', img: 'peppermills/peppermill.png', price: '60'  },
      64: { id: 64, productTypeId: 4, name: 'elm', desc: 'elm', img: 'peppermills/peppermill.png', price: '60'  },
      65: { id: 65, productTypeId: 4, name: 'indian redwood', desc: 'indian redwood', img: 'peppermills/peppermill.png', price: '60'  },
      66: { id: 66, productTypeId: 4, name: 'laminatedblue', desc: 'laminatedblue', img: 'peppermills/peppermill.png', price: '60'  },
      67: { id: 67, productTypeId: 4, name: 'laminatedgreen', desc: 'laminatedgreen', img: 'peppermills/peppermill.png', price: '60'  },
      68: { id: 68, productTypeId: 4, name: 'laminatedred', desc: 'laminatedred', img: 'peppermills/peppermill.png', price: '60'  },
      69: { id: 69, productTypeId: 4, name: 'laminatedsilverblue', desc: 'laminatedsilverblue', img: 'peppermills/peppermill.png', price: '60'  },
      70: { id: 70, productTypeId: 4, name: 'laminatedsilvergreen', desc: 'laminatedsilvergreen', img: 'peppermills/peppermill.png', price: '60'  },
      71: { id: 71, productTypeId: 4, name: 'laminatedsilverred', desc: 'laminatedsilverred', img: 'peppermills/peppermill.png', price: '60'  },
      72: { id: 72, productTypeId: 4, name: 'mahogany', desc: 'mahogany', img: 'peppermills/peppermill.png', price: '60'  },
      73: { id: 73, productTypeId: 4, name: 'oak', desc: 'oak', img: 'peppermills/shotgun.png', price: '60'  },
      74: { id: 74, productTypeId: 4, name: 'padauk', desc: 'padauk', img: 'peppermills/peppermill.png', price: '60'  },
      75: { id: 75, productTypeId: 4, name: 'spalted maple', desc: 'spalted maple', img: 'peppermills/peppermill.png', price: '60'  },
      76: { id: 76, productTypeId: 4, name: 'spalted elm', desc: 'spalted elm', img: 'peppermills/peppermill.png', price: '60'  },
      77: { id: 77, productTypeId: 4, name: 'walnut', desc: 'walnut', img: 'peppermills/peppermill.png', price: '60'  },
      78: { id: 78, productTypeId: 5, name: 'burmese redwodd', desc: 'burmese redwodd', img: 'peppermills/peppermill.png', price: '60'  },
      79: { id: 79, productTypeId: 5, name: 'catalpa', desc: 'catalpa', img: 'peppermills/peppermill.png', price: '60'  },
      80: { id: 80, productTypeId: 5, name: 'cedar', desc: 'cedar', img: 'peppermills/peppermill.png', price: '60'  },
      81: { id: 81, productTypeId: 5, name: 'cherry', desc: 'cherry', img: 'peppermills/peppermill.png', price: '60'  },
      82: { id: 82, productTypeId: 5, name: 'elm', desc: 'elm', img: 'peppermills/peppermill.png', price: '60'  },
      83: { id: 83, productTypeId: 5, name: 'indian redwood', desc: 'indian redwood', img: 'peppermills/peppermill.png', price: '60'  },
      84: { id: 84, productTypeId: 5, name: 'laminatedblue', desc: 'laminatedblue', img: 'peppermills/peppermill.png', price: '60'  },
      85: { id: 85, productTypeId: 5, name: 'laminatedgreen', desc: 'laminatedgreen', img: 'peppermills/peppermill.png', price: '60'  },
      86: { id: 86, productTypeId: 5, name: 'laminatedred', desc: 'laminatedred', img: 'peppermills/peppermill.png', price: '60'  },
      87: { id: 87, productTypeId: 5, name: 'laminatedsilverblue', desc: 'laminatedsilverblue', img: 'peppermills/peppermill.png', price: '60'  },
      88: { id: 88, productTypeId: 5, name: 'laminatedsilvergreen', desc: 'laminatedsilvergreen', img: 'peppermills/peppermill.png', price: '60'  },
      89: { id: 89, productTypeId: 5, name: 'laminatedsilverred', desc: 'laminatedsilverred', img: 'peppermills/peppermill.png', price: '60'  },
      90: { id: 90, productTypeId: 5, name: 'mahogany', desc: 'mahogany', img: 'peppermills/peppermill.png', price: '60'  },
      91: { id: 91, productTypeId: 5, name: 'oak', desc: 'oak', img: 'peppermills/shotgun.png', price: '60'  },
      92: { id: 92, productTypeId: 5, name: 'padauk', desc: 'padauk', img: 'peppermills/peppermill.png', price: '60'  },
      93: { id: 93, productTypeId: 5, name: 'spalted maple', desc: 'spalted maple', img: 'peppermills/peppermill.png', price: '60'  },
      94: { id: 94, productTypeId: 5, name: 'spalted elm', desc: 'spalted elm', img: 'peppermills/peppermill.png', price: '60'  },
      95: { id: 95, productTypeId: 5, name: 'walnut', desc: 'walnut', img: 'peppermills/peppermill.png', price: '60'  },
      96: { id: 96, productTypeId: 6, name: 'burmese redwodd', desc: 'burmese redwodd', img: 'peppermills/peppermill.png', price: '60'  },
      97: { id: 97, productTypeId: 6, name: 'catalpa', desc: 'catalpa', img: 'peppermills/peppermill.png', price: '60'  },
      98: { id: 98, productTypeId: 6, name: 'cedar', desc: 'cedar', img: 'peppermills/peppermill.png', price: '60'  },
      99: { id: 99, productTypeId: 6, name: 'cherry', desc: 'cherry', img: 'peppermills/peppermill.png', price: '60'  },
      100: { id: 100, productTypeId: 6, name: 'elm', desc: 'elm', img: 'peppermills/peppermill.png', price: '60'  },
      101: { id: 101, productTypeId: 6, name: 'indian redwood', desc: 'indian redwood', img: 'peppermills/peppermill.png', price: '60'  },
      102: { id: 102, productTypeId: 6, name: 'laminatedblue', desc: 'laminatedblue', img: 'peppermills/peppermill.png', price: '60'  },
      103: { id: 103, productTypeId: 6, name: 'laminatedgreen', desc: 'laminatedgreen', img: 'peppermills/peppermill.png', price: '60'  },
      104: { id: 104, productTypeId: 6, name: 'laminatedred', desc: 'laminatedred', img: 'peppermills/peppermill.png', price: '60'  },
      105: { id: 105, productTypeId: 6, name: 'laminatedsilverblue', desc: 'laminatedsilverblue', img: 'peppermills/peppermill.png', price: '60'  },
      106: { id: 106, productTypeId: 6, name: 'laminatedsilvergreen', desc: 'laminatedsilvergreen', img: 'peppermills/peppermill.png', price: '60'  },
      107: { id: 107, productTypeId: 6, name: 'laminatedsilverred', desc: 'laminatedsilverred', img: 'peppermills/peppermill.png', price: '60'  },
      108: { id: 108, productTypeId: 6, name: 'mahogany', desc: 'mahogany', img: 'peppermills/peppermill.png', price: '60'  },
      109: { id: 109, productTypeId: 6, name: 'oak', desc: 'oak', img: 'peppermills/shotgun.png', price: '60'  },
      110: { id: 110, productTypeId: 6, name: 'padauk', desc: 'padauk', img: 'peppermills/peppermill.png', price: '60'  },
      111: { id: 111, productTypeId: 6, name: 'spalted maple', desc: 'spalted maple', img: 'peppermills/peppermill.png', price: '60'  },
      112: { id: 112, productTypeId: 6, name: 'spalted elm', desc: 'spalted elm', img: 'peppermills/peppermill.png', price: '60'  },
      113: { id: 113, productTypeId: 6, name: 'walnut', desc: 'walnut', img: 'peppermills/peppermill.png', price: '60'  },
      114: { id: 114, productTypeId: 7, name: 'cocobolo', desc: 'cocobolo', img: 'peppermills/peppermill.png', price: '235'  },
      115: { id: 115, productTypeId: 8, name: 'steampunk', desc: 'steampunk', img: 'peppermills/peppermill.png', price: '235'  },
      116: { id: 116, productTypeId: 8, name: 'tripledome', desc: 'tripledome', img: 'peppermills/peppermill.png', price: '235'  },
      117: { id: 117, productTypeId: 8, name: 'dome', desc: 'dome', img: 'peppermills/peppermill.png', price: '235'  },
      118: { id: 118, productTypeId: 8, name: 'edison', desc: 'edison', img: 'peppermills/peppermill.png', price: '235'  },
      119: { id: 119, productTypeId: 9, name: 'dome', desc: 'dome', img: 'peppermills/peppermill.png', price: '235'  },
      120: { id: 120, productTypeId: 10, name: 'small', desc: 'small', img: 'peppermills/peppermill.png', price: '185'  },
      121: { id: 121, productTypeId: 10, name: 'medium', desc: 'medium', img: 'peppermills/peppermill.png', price: '235'  },
      122: { id: 122, productTypeId: 10, name: 'large', desc: 'large', img: 'peppermills/peppermill.png', price: '295'  },
    }
    penwoods: {
      'antler', 'cocobolo', 'mahogany', 'maple', 'cherry', 'dark', 'light', 'red', 'other'
    },
    penmetals: {
      'brassplain', 'brassengraved', 'copper', 'gunmetal', 'chrome', 'pewter', 'n/a'
    },
    otherwoods: {

    },

    market: {
      1: { id: 1, name: 'Millarville Market', organization: '', location: 'Millarville, AB' },
      2: { id: 2, name: 'Canmore Mountain Market', organization: '', location: 'Canmore, AB' },
      3: { id: 3, name: 'Banff Market', organization: '', location: 'Banff, AB' },
      4: { id: 4, name: 'Radium Market', organization: '', location: 'Radium, AB' },
      5: { id: 5, name: 'Invermere Market', organization: '', location: 'Invermere, AB' },
      6: { id: 6, name: 'Red Deer Spring Market', organization: '', location: Red Deer', AB' },
      7: { id: 7, name: 'Calgary Teacher Convention', organization: '', location: 'Calgary, AB' },
      8: { id: 8, name: 'Spruce Meadows International Christmas', organization: '', location: 'Calgary, AB' },
      9: { id: 9, name: 'Spruce Meadows Masters', organization: '', location: 'Calgary, AB' },
      10: { id: 10, name: 'Airdrie Christmas', organization: '', location: 'Airdrie, AB' }, 
      11: { id: 11, name: 'Red Deer Christmas', organization: 'Signature', location: 'Red Deer, AB' }, 
      12: { id: 12, name: 'Okotoks Christmas', organization: '', location: 'Okotoks, AB' }, 
      13: { id: 13, name: 'Vernon Creative Chaos', organization: '', location: 'Vernon, AB' }, 
      14: { id: 14, name: 'Calgary Art Market', organization: '', location: 'Calgary, AB' }, 
      15: { id: 15, name: 'Calgary Festival of Arts', organization: 'Signature', location: 'Calgary, AB' }, 
      16: { id: 16, name: 'Edmonton Butterdome', organization: 'Signature', location: 'Edmonton, AB' }, 
      17: { id: 17, name: 'Toronto One of a Kind', organization: '', location: 'Toronto, AB' }, 
      17: { id: 18, name: 'Ottawa Craft Show', organization: '', location: 'Ottawa, AB' }, 
      17: { id: 19, name: 'Millarville Christmas Market', organization: '', location: 'Millarville, AB' }
    }

    dayInfo: {
      1: { id: 1, marketId: 1, showDate: '2017-06-17' }
    }

    persons: {
      1: { id: 1, name: "Sean Matthews"},
      2: { id: 2, name: "Pete Tracy"},
      3: { id: 3, name: "Jan Tracy"},
      4: { id: 4, name: "Connor"},
      5: { id: 5, name: "Carol"}
    },

    transactions: {
      1: { id: 1, timestamp: 0900, dayInfoId: 1, user: 1, salesperson: 1, pp_or_pl: 'pp', total: 180, tax: 9}
    },

    transactionItems: {
      1: { id: 1, transactionId: 1, productItemId: 1, qty: 1, price: 75, tax: 4.25 },
      2: { id: 2, transactionId: 1, productItemId: 7, qty: 1, price: 95, tax: 4.75 }
    },

    dayInfoPersons: {
      1: { id: 1, dayInfoId: 1, personId: 1},
    },

    pens: {
      {'30/30 lever', 75, 'pens/lever.jpg'},
      {'30 cal', 75, 'pens/30cal.png'},
      {'50 cal', 55, 'pens/peppermill.png'},
      {'celtic', 95, 'pens/celtic.jpg'},
      {'cowboy', 85, 'pens/cowboy.jpg'},
      {'crystal', 45, 'pens/princess.jpg'},
      {'dragon', 95, 'pens/dragon.jpg'},
      {'firefighter', 120, 'pens/firefighter.jpg'},
      {'flyfish', 75, 'pens/flyfish.jpg'},
      {'harley', 95, 'pens/harley.jpg'},
      {'revolver', 95, 'pens/revolver.jpg'},
      {'shotgun', 95, 'pens/shotgun.jpg'},
      {'skeletonkey', 85, 'pens/peppermill.jpg'},
      {'skull', 85, 'pens/skull.jpg'},
      {'steampunk', 95, 'pens/steampunk.jpg'},
      {'stylus', 55, 'pens/stylus.jpg'},
      {'tech', 55, 'pens/tech.jpg'},
      {'victoriacross', 55, 'pens/victoriacross.jpg'}
    },
    'peppermills': {
      {'b_w_ebony', 150, 'peppermills/peppermill.png'},
      {'bubinga', 85, 'peppermills/peppermill.png'},
      {'burnt cedar', 75, 'peppermills/peppermill.png'},
      {'burmese redwood', 85, 'peppermills/peppermill.png'},
      {'burnt catalpa', 75, 'peppermills/peppermill.png'},
      {'burnt elm', 75, 'peppermills/dragon.png'},
      {'catalpa', 75, 'peppermills/peppermill.png'},
      {'cedar', 75, 'peppermills/peppermill.png'},
      {'cherry', 85, 'peppermills/peppermill.png'},
      {'elm', 75, 'peppermills/peppermill.png'},
      {'indian redwood', 85, 'peppermills/peppermill.png'},
      {'laminatedblue', 85, 'peppermills/peppermill.png'},
      {'laminatedgreen', 85, 'peppermills/peppermill.png'},
      {'laminatedred', 85, 'peppermills/peppermill.png'},
      {'laminatedsilverblue', 85, 'peppermills/peppermill.png'},
      {'laminatedsilvergreen', 85, 'peppermills/peppermill.png'},
      {'laminatedsilverred', 85, 'peppermills/peppermill.png'},
      {'mahogany', 85, 'peppermills/peppermill.png'},
      {'oak', 85, 'peppermills/shotgun.png'},
      {'padauk', 85, 'peppermills/peppermill.png'},
      {'spalted maple', 85, 'peppermills/peppermill.png'},
      {'spalted elm', 85, 'peppermills/peppermill.png'},
      {'walnut', 85, 'peppermills/peppermill.png'}
    },
    pizzacutters: {
      {'burmese redwood', 60, 'pizzacutters/peppermill.png'},
      {'catalpa', 60, 'pizzacutters/peppermill.png'},
      {'cedar', 60, 'pizzacutters/peppermill.png'},
      {'cherry', 60, 'pizzacutters/peppermill.png'},
      {'elm', 60, 'pizzacutters/peppermill.png'},
      {'indian redwood', 60, 'pizzacutters/peppermill.png'},
      {'laminatedblue', 60, 'pizzacutters/peppermill.png'},
      {'laminatedgreen', 60, 'pizzacutters/peppermill.png'},
      {'laminatedred', 60, 'pizzacutters/peppermill.png'},
      {'laminatedsilverblue', 60, 'pizzacutters/peppermill.png'},
      {'laminatedsilvergreen', 60, 'pizzacutters/peppermill.png'},
      {'laminatedsilverred', 60, 'pizzacutters/peppermill.png'},
      {'mahogany', 60, 'pizzacutters/peppermill.png'},
      {'oak', 60, 'pizzacutters/shotgun.png'},
      {'padauk', 60, 'pizzacutters/peppermill.png'},
      {'spalted maple', 60, 'pizzacutters/peppermill.png'},
      {'spalted elm', 60, 'pizzacutters/peppermill.png'},
      {'walnut', 60, 'pizzacutters/peppermill.png'}
    },
    icecreamscoops: {
      {'burmese redwood', 60, 'peppermills/peppermill.png'},
      {'catalpa', 60, 'peppermills/peppermill.png'},
      {'cedar', 60, 'peppermills/peppermill.png'},
      {'cherry', 60, 'peppermills/peppermill.png'},
      {'elm', 60, 'peppermills/peppermill.png'},
      {'indian redwood', 60, 'peppermills/peppermill.png'},
      {'laminatedblue', 60, 'peppermills/peppermill.png'},
      {'laminatedgreen', 60, 'peppermills/peppermill.png'},
      {'laminatedred', 60, 'peppermills/peppermill.png'},
      {'laminatedsilverblue', 60, 'peppermills/peppermill.png'},
      {'laminatedsilvergreen', 60, 'peppermills/peppermill.png'},
      {'laminatedsilverred', 60, 'peppermills/peppermill.png'},
      {'mahogany', 60, 'peppermills/peppermill.png'},
      {'oak', 60, 'peppermills/shotgun.png'},
      {'padauk', 60, 'peppermills/peppermill.png'},
      {'spalted maple', 60, 'peppermills/peppermill.png'},
      {'spalted elm', 60, 'peppermills/peppermill.png'},
      {'walnut', 60, 'peppermills/peppermill.png'}
    },
    seamrippers: {
      {'burmese redwood', 60, 'peppermills/peppermill.png'},
      {'catalpa', 60, 'peppermills/peppermill.png'},
      {'cedar', 60, 'peppermills/peppermill.png'},
      {'cherry', 60, 'peppermills/peppermill.png'},
      {'elm', 60, 'peppermills/peppermill.png'},
      {'indian redwood', 60, 'peppermills/peppermill.png'},
      {'laminatedblue', 60, 'peppermills/peppermill.png'},
      {'laminatedgreen', 60, 'peppermills/peppermill.png'},
      {'laminatedred', 60, 'peppermills/peppermill.png'},
      {'laminatedsilverblue', 60, 'peppermills/peppermill.png'},
      {'laminatedsilvergreen', 60, 'peppermills/peppermill.png'},
      {'laminatedsilverred', 60, 'peppermills/peppermill.png'},
      {'mahogany', 60, 'peppermills/peppermill.png'},
      {'oak', 60, 'peppermills/shotgun.png'},
      {'padauk', 60, 'peppermills/peppermill.png'},
      {'spalted maple', 60, 'peppermills/peppermill.png'},
      {'spalted elm', 60, 'peppermills/peppermill.png'},
      {'walnut', 60, 'peppermills/peppermill.png'}
    },
    corkscrews: {
      {'burmese redwood', 60, 'peppermills/peppermill.png'},
      {'catalpa', 60, 'peppermills/peppermill.png'},
      {'cedar', 60, 'peppermills/peppermill.png'},
      {'cherry', 60, 'peppermills/peppermill.png'},
      {'elm', 60, 'peppermills/peppermill.png'},
      {'indian redwood', 60, 'peppermills/peppermill.png'},
      {'laminatedblue', 60, 'peppermills/peppermill.png'},
      {'laminatedgreen', 60, 'peppermills/peppermill.png'},
      {'laminatedred', 60, 'peppermills/peppermill.png'},
      {'laminatedsilverblue', 60, 'peppermills/peppermill.png'},
      {'laminatedsilvergreen', 60, 'peppermills/peppermill.png'},
      {'laminatedsilverred', 60, 'peppermills/peppermill.png'},
      {'mahogany', 60, 'peppermills/peppermill.png'},
      {'oak', 60, 'peppermills/shotgun.png'},
      {'padauk', 60, 'peppermills/peppermill.png'},
      {'spalted maple', 60, 'peppermills/peppermill.png'},
      {'spalted elm', 60, 'peppermills/peppermill.png'},
      {'walnut', 60, 'peppermills/peppermill.png'}
    },
    shavingkits: {
      {'cocobolo', 235, 'peppermills/peppermill.png'}
    },
    lamps: {
      {'steampunk', 235, 'peppermills/peppermill.png'},
      {'tripledome', 235, 'peppermills/peppermill.png'},
      {'dome', 235, 'peppermills/peppermill.png'},
      {'edison', 235, 'peppermills/peppermill.png'}
    },
    clocks: {
      {'dome', 235, 'peppermills/peppermill.png'}
    },
    maps: {
      {'small', 185, 'peppermills/peppermill.png'},
      {'medium', 235, 'peppermills/peppermill.png'},
      {'large', 295, 'peppermills/peppermill.png'}
    }
  }
}